export const words = [ 
"Albicocca", "baccello", "ciliegia", "dado", "elefante",
"farfalla", "gatto", "hotel", "iguana", "jacuzzi", "kiwi", "lampada", "mare", 
"nuvola", "orso", "pinguino", "quadro", "rana", "sedia", "tigre", "uccello", 
"vaso", "waffle", "xylofono", "yogurt", "zaino", "anatra", "banana", "cappello",
"delfino", "elefante", "fiore", "giraffa", "hamburger", "isola", "jeep", "koala",
"leone", "montagna", "nave", "ombrello", "panda", "quercia", "riccio", "stella",
"tartaruga", "uva", "violino", "waffle", "xilofono", "yogurt", "zanzara",
"alligatore", "babbo natale", "coccodrillo", "dattero", "elefante", "foglia", 
"gabbiano", "ippopotamo", "jeep", "koala", "leopardo", "mangusta", "noce", "orologio",
 "panda", "quaderno", "riccio", "scimmia", "tigre", "unicorno", "viola", "zebra", "ananas",
  "barca", "cane", "dado", "elefante", "fragola", "giraffa", "hula hoop", "iglù", "jolly", 
  "koala", "limone", "mela", "nuvola", "orso", "pesca", "quadro", "rana", "scoiattolo", "tigre",
   "unicorno", "valigia", "zaino", "albero", "balena", "caramella", "delfino", "elefante", "fico",
    "giraffa", "hamburger", "isola", "jeep", "kiwi", "luna", "mela", "nuvola", "orso", "pesce", "quadro",
     "rana", "scooter", "tigre", "unicorno", "vino", "zucchero", "anatra",
"banane", "cavallo", "delfino", "elefante", "fragola", "gabbiano", "hot dog",
"isola", "judo", "koala", "limone", "mela", "nocciola", "orso", "panda", "quadro",
"riccio", "scoiattolo", "tigre", "uva", "volpe", "zanella","pizza","surf","voli"]